<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Modify_By_Section.aspx.cs" Inherits="Time_Table.Modify_By_Section" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel=
    "Stylesheet" href="CSS/StyleSheet1.css" />
     <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
     <script>    function Show_notify_btn() {
                var divv = $("#notify");

                var top = Math.max($(window).height() / 2 - divv[0].offsetHeight / 2, 0);
                var left = Math.max($(window).width() / 2 - divv[0].offsetWidth / 2, 0);
                divv.css({ top: top, left: left });
                divv.fadeIn(500).delay(1500).fadeOut(700);
              
            }

            </script>

</head>
<style>
 body
{
    
    background-image:url('Pics/LP-Page-color2.jpg');
    background-repeat:no-repeat;
    background-attachment:fixed;
    background-position:center;
   

              
     font-family: "Century Gothic", CenturyGothic, AppleGothic, sans-serif;
}
</style>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
        <ContentTemplate>
         <div class="round-button" style="float:right; right:0;">
    <a href="Time_table_manager.aspx">
        <img src="http://codeitdown.com/media/Home_Icon.svg" alt="Home"  />
    </a>
</div>

        <center><img src="Pics/lpu_logo.png" /></center>
        <center><asp:Label runat="server" ID="notify" CssClass="myLabel"   Font-Bold="True" style="padding:2%; position:absolute;"  Font-Size="Medium" ForeColor="#FF9933" Visible="False" Width="50%"></asp:Label></center>
       
        <br />
        <center>
            <asp:GridView runat="server" ID="GridView_Sections" 
                AutoGenerateColumns="False" AutoGenerateDeleteButton="False" 
                AutoGenerateEditButton="False" onrowediting="GridView_Sections_RowEditing" 
                onselectedindexchanged="GridView_Sections_SelectedIndexChanged" 
                onrowdatabound="GridView_Sections_RowDataBound" 
                onrowcancelingedit="GridView_Sections_RowCancelingEdit" 
                onrowupdating="GridView_Sections_RowUpdating" Font-Size="X-Small" 
                onrowdeleting="GridView_Sections_RowDeleting">
        <Columns>
        <asp:TemplateField HeaderText="Section_Number">
    <ItemTemplate>
         <asp:Label runat="server" ID="Section_Number" Text='<% #Eval("Section_Number") %>'></asp:Label>
        </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Course Code">
    <ItemTemplate>
         <asp:Label runat="server" ID="Course_Code" Text='<% #Eval("Course_Code") %>'></asp:Label>
        </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Course_Title">
    <ItemTemplate>
         <asp:Label runat="server" ID="Course_Title" Text='<% #Eval("Course_Title") %>'></asp:Label>
        </ItemTemplate>
        </asp:TemplateField>
        <asp:BoundField DataField="L" HeaderText="L" ReadOnly=true />
        <asp:BoundField DataField="T" HeaderText="T" ReadOnly=true  />
        <asp:BoundField DataField="P" HeaderText="P" ReadOnly=true />
        <asp:BoundField DataField="Groups" HeaderText="Groups" ReadOnly=true />
        <asp:TemplateField HeaderText="TL">
    <ItemTemplate>
         <asp:Label runat="server" ID="TL" Text='<% #Eval("TL") %>'></asp:Label>
        </ItemTemplate>
        </asp:TemplateField>
       <asp:TemplateField HeaderText="TT">
    <ItemTemplate>
         <asp:Label runat="server" ID="TT" Text='<% #Eval("TT") %>'></asp:Label>
        </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="TP">
    <ItemTemplate>
         <asp:Label runat="server" ID="TP" Text='<% #Eval("TP") %>'></asp:Label>
        </ItemTemplate>
        </asp:TemplateField>
        <asp:BoundField DataField="Course_Domain" HeaderText="Course_Domain" ReadOnly=true />
        <asp:TemplateField HeaderText="Hash Code">
    <ItemTemplate>
         <asp:Label runat="server" ID="Hash_Code" Text='<% #Eval("Hash_Code") %>'></asp:Label>
        </ItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Feculty Name">
    <ItemTemplate>
         <asp:Label runat="server" ID="Feculty_Name" Text='<% #Eval("Feculty_Name") %>'></asp:Label>
        </ItemTemplate>
        </asp:TemplateField>
         <asp:TemplateField HeaderText="U.ID">
    <ItemTemplate>
         <asp:Label runat="server" ID="UID_label" Text='<% #Eval("UID") %>'></asp:Label>
        </ItemTemplate>
    <EditItemTemplate>
        <asp:DropDownList ID="Uid_Drop" runat="server" OnTextChanged="Add_Name" AutoPostBack="True" CssClass="myButton">
        </asp:DropDownList>
    </EditItemTemplate>
    </asp:TemplateField>
         <asp:TemplateField HeaderText="Action">
     <ItemTemplate>
     <asp:LinkButton ID="LinkButton1" CommandName="Edit" CssClass="myButton" runat="server"  Text="Edit" />
     </ItemTemplate>
     <EditItemTemplate>
      <asp:LinkButton ID="add_button" runat="server"  CommandName="Delete"   Text="Add" Enabled="False" CssClass="myButton"></asp:LinkButton><br /><br />
      <asp:LinkButton ID="update_button" runat="server"  CommandName="update"   Text="Update" Enabled="False" CssClass="myButton"></asp:LinkButton><br /><br />
      <asp:LinkButton ID="Cance_button" runat="server" CommandName="Cancel" CssClass="myButton_edit" Text="Cancel"></asp:LinkButton>
     </EditItemTemplate>
     </asp:TemplateField>
        </Columns>
        
        </asp:GridView>
        </center>

        </ContentTemplate>
        </asp:UpdatePanel>
    </div>
    </form>
</body>
</html>
